# Generated by Django 4.1.3 on 2022-12-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0002_wordle'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordle',
            name='board',
            field=models.TextField(default='\n             -----\n             -----\n             -----\n             -----\n             -----\n             -----\n         '),
        ),
        migrations.AlterField(
            model_name='wordle',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
